### ISSUE TITLE
[Feature Request] Add the option to display the control bar in a vertical orientation  

### ISSUE THREAD

**Issue by iamjoshlee** [luvmex/Sketch-Guides#4]
Guides are a very crucial and frequently used tool for me, so I often like to leave Sketch Guide's control bar open so that it's easily accessible. I have found that, more often than not, its horizontal orientation tends to get in the way for me. It would be very beneficial for users to have the ability to toggle between horizontal and vertical orientations for the control bar (or even just collapsing it as a whole into a small square). This would allow the user to retain as much space as possible to focus on artboards, while still maintaining the ease of accessibility that this wonderful plugin's control bar offers.

**Comment by luvmex** [comment]
Thanks for your experience feedback, and sorry for the late reply.

I'm glad this plugin work for you and help you to create more UI things.
But I'm sorry I don't have too much time to handle this project.

I will keep this feedback in mind, if possible I will revise it again.
